language: java
before_install:
  - find .
  - "./gradlew wrapper"
  - ls -la gradle/wrapper/gradle-wrapper.jar

jdk:
  - oraclejdk8


notifications:
  email: false


before_deploy:
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gnEIYyi4HCSasMWkDOJ6FSLGi+utmV2gr4e4AZl2/ut4V1g84KF9vvtcXKT5LVEChABSKNhp3wkOks9WihIvF/QNefrB6js60YDC2WrdTvW8crQuzYpZvTNdGNfEiJFOm0NOt2GfAAQxTGlY9zc+A/3CHRCts6bg8oitGftwUJNhwPsj4q4AjiepUD0VON8ccJzyesMVPBiBk9FZlQDFgiuzk8QOz+EKR4XmAV6Hz/ELB5t8mBWNiBE6FQ0lb595F8kZapp4HkXGrmQRltP7PxHoacKyh/VGyirBBsQV5H4dkrnvNjowU7PvebwNGT+6ZDRrD4AYyOzPMtw8qSfJICxkYHRe1Frje78T/K5Hx/6r3q5vTPrm89Ru8MjxaOJjZlygLOKHGZAqAsOU/tdBGJ8G580/rj/31keb5hKXJOMJJikUmwwVRUOM3a0FqmrP+4ZDkBKBXR1hKHtoTayogbIzFyF7QvseSs11CcGnRpZuLvSJtC6dunH/4bEq2cJfnhtfMWrgka3FilY9+jkuGYuOe5/1nUCR6e0Iatj8ULPV2aMxFBupqLEf1vs8/SkZTHoqM0QSeDOsYQVkTMERhlW+HDB+9hTLmgdN0t3Bjlx/ojFmlrGNvnITPMmMDOK795hL1Tzm1Vn8EeKJF+T/NQFt2ZN76w4svTMBUg4VWRk=
  file: "build/libs/scheduler2ics-1.0.jar"
  on:
    repo: rogerGunis/scheduler2ics
branches:
  except:
    - "/^*-v[0-9]/"
