dist: trusty
sudo: required
addons:
  chrome: stable
language: java
before_install:
- ls -la gradle/wrapper/gradle-wrapper.jar
- openssl aes-256-cbc -K $encrypted_cff167bd1238_key -iv $encrypted_cff167bd1238_iv
  -in icalToGoogleDeployment/src/test/resources/client_secrets_apiKey.json.enc -out
  icalToGoogleDeployment/src/test/resources/client_secrets_apiKey.json -d
jdk:
- oraclejdk8
notifications:
  email: false
after_success:
- export ICS_BUILDER_JAR_FILE=$(find . -name "jobService.jar")
- export HOLIDAY=$(find jobService/src/ -name "Holidays.csv")
- export JOB=$(find jobService/src/ -name "JobDescription.csv")
- export WORKER=$(find jobService/src/ -name "Workers.csv")
- java -jar ${ICS_BUILDER_JAR_FILE:-} --workers ${WORKER} --outputFilePath /var/tmp/schedule/
  --jobDescriptions ${JOB} --holidays ${HOLIDAY} -log INFO --withPostprocessing
- echo "Checking for necessary allEvents.ics file"
- find /var/tmp/schedule -name "allEvents.ics" | grep -q allEvents.ics || exit 1;
- echo "found one"
- java -jar -DACCOUNT_USER=$ACCOUNT_USER ${DEPLOYER_JAR_FILE:-} --icsDirectory /var/tmp/schedule/
  --apiKey icalToGoogleDeployment/src/test/resources/client_secrets_apiKey.json -log
  INFO
- make geschwisterTag
- make createPdf
- zip -r postProcess.zip /var/tmp/schedule
- cp /var/tmp/schedule/allEvents.pdf .
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${BLUB}@github.com/rogerGunis/schedule2ics --tags
after_deploy:
- test -f /var/tmp/schedule/${CALENDAR} && jobService/src/main/resources/WithPostProcessing/bin/IcsFileSync.sh
  /var/tmp/schedule/${CALENDAR}
deploy:
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: RSzwQ5LbgJWa/GZyryOSP8UvIhcPErbImsZQkn7z9xPNguIkHId8vVTMMxwq2Aghsyl/sOFAFMB94Rw+ESyYkoCiUA5GEx5KpF/YNa2nRRb3L1Z10BHtRV4xAnGMap1MECA1oVVcSjRA5S8f0K8rpr/ogzzpHVzud4NhbzYVMbwtLxpQiS0GhFergR9UL6FChNYseMSJWd/cjDCvJc07afPXp4aSCA7RfnI92KazHntKaOy8C17fOxyBRITDCd1giZB+DXG7rRAIJm8eUIqcKgwwidALmjeoDy6J4CiddtexILa0+QoQDdRQ70hohFcpM2hO/HwSgHxj1WY4Us4kKVHFu6rvewVwD6RMct7iSCYRCCKprVUqR7GJXRbn6KZIqCsSsclKOofkkc9oQqcH83c8Z3guv0jI971EmRaMNO+T1XkoLCtGKSHmGp/W6hUnzqtC8o87KI13/wzdhiXeAtHfvAa6qhwB/rRYnvaBWfjKmYRDhE9hMfEcDTIRpXuAF3My2enOtYgrptic5rYDV74C0UhzIVCcFsqBVP+gH+qLWkekql2YGxBDbp3AarrUbh+LYGQTXscBXJdmGLNgzeJEIM+our9xB+cIKfiQW/RD4KazwjnuGYYp8Mls/sly4ivYxmIqByRRcL2vRGmFERgl+cHcMZX/9wRdFbog8mE=
  file_glob: true
  file:
  - postProcess.zip
  - allEvents.pdf
  on:
    repo: rogerGunis/schedule2ics
branches:
  except:
  - "/^*-v[0-9]/"
env:
  global:
  - secure: YAFpcOiggtffRjErCiDhVDdLCoCwL5yJhBg1OP7+BCoT9QcNlL449zTeKDIz/8F6Q1e+OOLNzcGM6c7sHBgZRyTlfKsa1JDevQixqqp6TsE69KCVg/ocMew2OByC3MoJiVSIfDekdJ0DeYq3bfRB+4H6vUnvVgFer/3TckcHlIGXxrF6w+21EGt5BqjAUq+cH4rCS3svtDa90G9g2kCls+aExk4FLY2P3hhHjulf4qUDd9k37LpuyV5UmM4TN45xbt4etvsbx59OMfkGgka0QcKF8mftVbJeYUdHmcRFSVBIebtAqqGqTweXWyHYy7xUOE0hmWK/Wh7GZKPDbXNYkgsOoeOClSKcaIGy49Dd3I9M/csRObV87LfpJJNxdGop1Fqv51Koycu2NtpOtC5Jv13wqDPEegvFZiPPYpOYdWfOIJQ80HHSLcw/4bO3IxZ/VZDY66AFQKB6DvDkoFjY/VSoXsncdZZ0SH43VeELCuZiapbl1GQtDK9Us//WSq323IfGLA9joVLbgBCuCibGbJM4FksdNjO9wXceI7V+yf/LUpLMlXtk3kR/8FECjcppPGxdjWi2mmNzJc91XiEapG95Cyjt9VbJMmNXr8BQFH84NEnbJ/fA4Oq3QCEWk7beil3slCr4JRTq2UCIwO7nwG/iPGe4ljoyWeoDsVCzvwQ=
  - secure: CLK1ioeu+3DgH1Zw7/35JF8GGMsSB0JRuuYW0SXPnFIPp8tIR0XDqcrs4V1qdOJcfqJ34IG46cmAPa45ZrurT0HA+BIr/xR5tYy0Z7qO1oWeRLhFGaC0UavBVVnWRF7WpTAOGpLHp6q96xegzEFki85hHPUqHC7+GsFo3UiHDQnT4qgOwAMLIdrBm0HS7R54q7OLS6oiynyTc6KbyeXFoFCkF8Dvyoh8K1ZCcDQ+7Y//TPpnrGAdfPLv2kRVX7MYGS/gpescfivRcYBeZX91jlsFAU4tNVz2V0E6+GTcdP2s7OqMCbd81NiN6zOmvMlEav5rU1AIYJePP3rqIbZK7MYxhTQVgHiUNYpioDhcOabpOCG3C+nX/yD5mpg+rVB0QHOR9m8X9xKxnvmy0OJxXzzJrb2fwrtOCwRjjes7zap9R8a+Yjm+SfkR3uoxErijmyAIdER7xjvzuxLwoShif+vZ20CpSwJWfZX2GOAGrXKo+/arC5ty49Prt0PXVUBLWtj3SU00Ln6WBAZi/AfJ6n0Z/bFhNIGKEzQx5EAdy9AhGKNjcFuCxo7pI31/eDb5vsEiA3GZ3JTCosHFIBq+FLv830InMlxDOPEOuy9ROGVmduOzke07U3t19sOG/OHIfhlsjUhERPcDgtg//K5Szb4hO6D3eIHEBEbM/ljW/IU=
  - secure: SMCPZ+pNyrEuMvhXxPtgcfZu1NBNd2aj1iNteGslNvLbIeTXZMpdYXIXkU3iBU0A8asM5cLUdeuVHKhKu9TfaS9y+dR10rfMeMHbLZcsxuBgrFeFKITCV/c8pUFptWTfZssE5HKl3QLG7syxm/UrkZWLrHCNlVuZUO8u4OE2xSUwh3MdkbHROp3hkwhB6WkSv4ZDOmFIZL03NVN078DmLZaShci3xw1q6Y/L0SoSH7qldgOIecaTOKs/AcND4VK2U+MQBRTe7xxgoPin97zmW7g0Pn2b2o2plKb4qvrNubwrkzRfWoHhzZCejeuC4UF+jkertplli5Pz6n/6oS7g23SVmMOFehU9Fb/C/yERKHaMTM9OZ6W9C2c4Dfvp2knzKubLM2bW5ki2EE5//6tuQcEquLUXmFTAW/EGZG9hrzIgaPkS93UWX1DFzHrNvjuAuH52x4GluZS6AfJjSjmSg1DzCi7Gj1GfT4bsHYC1inho3eNKumIYxJKBfvcbIq9vIzuzJUQQnrbgeptWZCl7RU0fNsGbz5u+3TEqLH5bAt9TNlEXN4cbdaa9wscHV5fys9cyk5M/7VnnlWeZvkVGwXkC9PJcnXAeCOxB8yVrJ+oAF8bvyIk0Fv9dvNbJNMbQ89qP0j9WYKxdjaH9ILPJNfLInh35nCWpBsTLevVqXL4=
  - secure: Brfgyf08o+p1+8YLEQ3mdYrZ1qkQjHrG6W29ob774GstTWGStRQfPljvLgkg11psolKpNiDJDWtk1TqzQ68szoxLOi+08/edlT+wMaLDEjedr7+dJFrMHJbU95ijECDhKHc0wXpUnZKnrBbhKpypolrHL2tgmFF61IO0vZFwomfCXmFy4kBJvOaDzIg4ydmpNeSSNfDErgCeC4R+LGXq5TlxrrbVtqBOJgPLlMHBtu0fH6W86gWo7dh3DgfJI4cyv1K6wE8OmFBm6W6Op+Ic1TdFFBUfW8U9qoZ01xNc9R20Amyv8SGLQffVYTMRGSLEWvjN1RF45/7gM95ubPnfzKqWaKDtCthAUlwY865qig9PYELjprZsxi8hTH18bsP6B2qzW1IAs6XTfofS5DGPKxDvsBY9X3OeTRPWLcvd1vg0smcni+zKRagYSXDB9pSr7oEVVEO3NOPhkYjxLCTClV4yOpwovYv4hm9H2G5lkZsW4+czqsixeTaIDBuPDhDU7r+3o7Fth/OBNlHqDLIyVTvmjtjIjIXl5ZQN8H5SxD5/B5OrGyajoKQjr2edHBws98JFmaTmxK0SAs0o/I/xN2AQZns62gR5IuVk1wI5YWZuXP3EasFEKvGACOptnZSbWd0VN1hZLrAbg9mk5bcHjAa0WbUPcj4xkFGkW5QNvTQ=
  - secure: Uaxj9Iu7K/Cx7/xcxdTHliTaKn72Er1JtV12m5hpXUwtfynz65Z0UnP1LgZPCxRg07ZokSXZNxgY3XRHQ+rtl+L3ZFolj610G1Tm4adZqh9D6Hh6bJrOQ3Pu/acH9r5Q0YgXHVwlsPhjfEs0yHpKGwz/AqVDpVvQEX37R0iRTCo7wpA18OudOndaVAQWODT3Txo0uYECPlaToMIM6KiTvHWUOicXVNFD5xmBLA4vqVWJxQ3wTkSVyG+/Y4I9MSVe2JTziwL13+NGF7hyUSE3jXzY1HmDlOq8LOVuBKTdxEFF7hygSNt56AnMcDyIa50yrCwd6vH0K/sBqjmWTAH0oxBp/HWaz5QQIs0fs9TKhuA3VuvBzwkkHnh3Gsr97RMfjNTLjq6kDk6b+GuBwk+/MDWW0+9LtejkT5dtK1kqkptZIEFaO8Tw/P7cHl5XVaC5Vavw8+tRVdNrq/AI4865BkK42mtwCOuNPDMCxZYhgPFv52n0CEsLU8XOmls63eI8v9qZ09azq2IoUBdiGVqk8yWADWdCHdVZtokcrLnmMY3X9N1QgN6dzBZe+koj1B+iywIlRaDws75+WdgIG5na+8yFEfdj1Ewt20JKm88fsuCstZ2vRzqK+hDzLBtRojIMNQXqGhWItcNsxFtWxuJn2sl4ik5BUaXdDGfo2OEnnmw=
  - secure: by7IM8pDknauc16SRh2uT6Aukb2nBBuFHJ2AMJ4v3c3Uzv59jUrRxrkMRJarI/meKArud1v0ZEb+RP9gUCPHd2ub9CQetwzzL8zuPa8jaLCSkUyQ9G+8BcveX6UuFVXEMuok1CutrByI1MVF3bkdkkaS4tSw7LTuQ3e7XfYOcVzD5ICUAfvkKibPLzYKYV06VVAj9UeWqxZ9PhbiEt3aRwuHBRn9lb1o9UjSI7/Hl9QO0QNDNp8tI595pS5s3zMmsRonUlPnO6vdtfsU5LGyXiTybZcyd+4W9AqqE0EupHTgB8OWPd4b4rizwGYEnygiNY9E1+iadh2qJvaCE5o6gcKbldplfwbeimkUARLiFXxW/KQd7XOfav9+PTME6MIxa8sY/GOEZhAF/EvvOP1d/NoCOChNIPUv8cPcQ39dwPdVDJ3RidnHndb3D5+CXrZvZ6/ADq4XXy2cv87IDHTB3Yb9+LtiLwVkBmU1jqhlgtyRubVufWn7IeygI79Wn/uLM8wFBeOqsG6fVrxDrEzfdzn9i/zNo8oP9TNZTYSQkoW85mQ/dJ57avS8hzLz2sMJGGmaQSmHzr8mFUeYzjPVuV27BNEqIBlCJVdV5JTS63Wbu1ZLc44cke82tDbfPWKqbOWMaU5L8YWmHkWIcqwnXCWVrtd/kbI98hFxMzM8H8s=
