language: java
before_install:
# - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# - sudo dpkg -i ./google-chrome*.deb
# - sudo apt-get install -f
- "./gradlew wrapper"
- ls -la gradle/wrapper/gradle-wrapper.jar
jdk:
- oraclejdk8
notifications:
  email: false
# before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq libical1a
after_success:
- java -jar build/libs/scheduler2ics-1.0.jar --workers $PWD/src/test/resources/WithPostProcessing/inputData/Workers.csv --outputFilePath postProcess --jobDescriptions $PWD/src/test/resources/WithPostProcessing/inputData/JobDescription.csv --holidays $PWD/src/test/resources/WithPostProcessing/inputData/Holidays.csv -log ALL
- export LD_PRELOAD=$PWD/src/test/resources/WithPostProcessing/lib/libical.so.1.0.1
- $PWD/src/test/resources/WithPostProcessing/bin/ics2html postProcess $PWD/src/test/resources/WithPostProcessing/bin/
- find src -name "jquery.min.js" -exec cp -v \{\} postProcess \;
- find src -name "calendar.css" -exec cp -v \{\} postProcess \;
- zip -r postProcess.zip postProcess
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${BLUB}@github.com/rogerGunis/scheduler2ics --tags
deploy:
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: i3/wiZDPAc8P4u/Znd4lbd1bE8UrcvknqsvybxQfAX0ZUADZpFoMeVzxAJXxwGFzxQZKhMmGu15zXpYdWLx3yQT7C504ioN5XgzLBEb/Xd2ESZxN0R0Js7U59Qq5VrgD/T5KUY5qWCyWuGpeqSH1mA+LOc9EJ0cEV5l/aXH0UkwjWa9T9VQ/vxeHfjiU3HC91RLudHWw0/kg3oUi5P9YMgS/tiN3JFygiwGSAapkmLZS1yROVK3oR6o4Kg3fW1dWkJlRCOQWf3Mr4cOHUNLq/S6T4m9koZNmHIZ7Z6JZnsn43UQVDb0CVXMoewWl6T17TZJVc7rEJFU7Rbfs7J9V4ikci1KcofICpMEKoupFpS9kXoFWA5UTIJ2djNZOSjcwOxEVZ2Kw6KH5uNgIt2NkSby78rqpWPMcQCRi1Qmxy2k7/R3yFUft0PzhQOV0nelnqAqADQRBVVnhAaRGMIPSW8MLfMl4tzHL8Ok8oNAtUXKWIy3mLoE0rLR9Z6JzsAzD/kytrGvgw92eGzJX4aM75IIid+AFs47+EYoPQmeIZuvkZfz98zK88zbSNNLqZK2SqXm3e2oJcUWqkW+upmWknt6U5RsQbxN+qZPpjbdMETqP63AchIzCaK0Lm3w3lecC81Qaa/kv+SpOD2uBsw7G7923eBk95A8bVq2c2ekoukU=
  file_glob: true
  file:
   - "build/libs/scheduler2ics-1.0.jar"
   - "postProcess.zip"
#   - "postProcess/allEvents.html"
#   - "postProcess/calendar.css"
#   - "postProcess/jquery.min.js"
#   - "postProcess/Martina+Roger.ics"
#  local_dir: postProcess
  on:
    repo: rogerGunis/scheduler2ics
branches:
  except:
  - "/^*-v[0-9]/"
env:
  global:
    secure: YAFpcOiggtffRjErCiDhVDdLCoCwL5yJhBg1OP7+BCoT9QcNlL449zTeKDIz/8F6Q1e+OOLNzcGM6c7sHBgZRyTlfKsa1JDevQixqqp6TsE69KCVg/ocMew2OByC3MoJiVSIfDekdJ0DeYq3bfRB+4H6vUnvVgFer/3TckcHlIGXxrF6w+21EGt5BqjAUq+cH4rCS3svtDa90G9g2kCls+aExk4FLY2P3hhHjulf4qUDd9k37LpuyV5UmM4TN45xbt4etvsbx59OMfkGgka0QcKF8mftVbJeYUdHmcRFSVBIebtAqqGqTweXWyHYy7xUOE0hmWK/Wh7GZKPDbXNYkgsOoeOClSKcaIGy49Dd3I9M/csRObV87LfpJJNxdGop1Fqv51Koycu2NtpOtC5Jv13wqDPEegvFZiPPYpOYdWfOIJQ80HHSLcw/4bO3IxZ/VZDY66AFQKB6DvDkoFjY/VSoXsncdZZ0SH43VeELCuZiapbl1GQtDK9Us//WSq323IfGLA9joVLbgBCuCibGbJM4FksdNjO9wXceI7V+yf/LUpLMlXtk3kR/8FECjcppPGxdjWi2mmNzJc91XiEapG95Cyjt9VbJMmNXr8BQFH84NEnbJ/fA4Oq3QCEWk7beil3slCr4JRTq2UCIwO7nwG/iPGe4ljoyWeoDsVCzvwQ=
